# code to explore Knockout Experiment data, as generated by "run_KO.R".
# "run_KO" generates a jags output object for every species x year x KO combo.

library(ggpubr)
library(tidyverse)

#cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

latlong <- read.csv("models/input/latlong.csv", header = F, col.names = c("siteid", "lat", "long"))

my_files <- list.files(path = "./COMB_minimal/results/jagsResults/jagsResult_burn_covar/", pattern = "*.RData", full.names = T)
all_data <- lapply(my_files, load, .GlobalEnv)

# BIG LOOPS --------------------------------------------------------------------

extract_species <- function(obj_name) {
  strsplit(obj_name, "_")[[1]][2]
}

# Group JAGS objects by species
species_groups <- split(ls(pattern = "jagsResult"), sapply(ls(pattern = "jagsResult"), extract_species))

species_datasets <- split(ls(pattern = "data_"), sapply(ls(pattern="data_"), extract_species))


# Loop for generating naive occupancy tables ------------------------------

naive_occs <- list() # empty list for species' naive occs

for (species in names(species_datasets)) {
  species_dat <- mget(species_datasets[[species]]) # for making a table 

  for (species in names(species_dat)) {
  data <- species_dat[[species]] # obj is a single model
  
site_pos <- data.frame(naive.pc.n = rowSums(data$y.pc, na.rm=TRUE), naive.aru.n = rowSums(data$y.aru, na.rm=TRUE))
site_pos$naive.pc.pa <- ifelse(site_pos$naive.pc.n==0,0,1)
site_pos$naive.aru.pa <- ifelse(site_pos$naive.aru.n==0,0,1)
site_pos$both <- site_pos$naive.pc.pa + site_pos$naive.aru.pa
site_pos$either <- ifelse(site_pos$both > 0, 1, 0)
site_pos$siteid <- as.numeric(rownames(data$y.ind[,]))
site_pos$common_name <- substr(species, 6,10) # need to extract the 4-letter code from "data_XXXX"
site_pos$year <- year

naive_occs[[species]] <- site_pos
}
}
all_naive_occs <- do.call(rbind, naive_occs)

tab <- left_join(latlong, all_naive_occs)
write.csv(tab, file = "COMB_minimal/results/NAWA_naiveOcc_2020_20250718.csv")

# det_tbl <- data.frame(mean = colMeans(site_pos[3:6], na.rm=T), 
#                       model=colnames(site_pos[3:6]), 
#                       measure="naivePsi") # how close the pc and aru estimates are to the combined model estimates likely differs by species

# define color scheme for models
# my_colors <- c("H" = "#0072B2",
#                "HA" = "#76B7B2",
#                "HS" = "#59A14F",
#                "HAS" = "#E69F00",
#                "A" = "#D55E00",
#                "AS"="#FF9DA7",
#                "S"="#E15759")

my_colors <- c("H" = "#59A14F",
               "HA" = "#76B7B2",
               "HS" = "#0072B2",
               "HAS" = "#CC79A7",
               "A" = "#E15759",
               "AS"="#FF9DA7",
               "S"="#E69F00")

# Loop for generating parameter figures -----------------------------------

for (sp in names(species_groups)) {
  species_mods <- mget(species_groups[[sp]]) # "species_mods" is a list of all models for that species 
  species_summs <- list() # empty list for all model summaries of a given species
for (mod_name in names(species_mods)) {
  obj <- species_mods[[mod_name]] # obj is a single model

mod_summary <- data.frame(obj$summary)
mod_summary$model <- paste(str_split(mod_name, "_")[[1]][4],str_split(mod_name, "_")[[1]][5], sep="_")
mod_summary$measure <- rownames(mod_summary)
mod_summary$species <- sp

species_summs[[mod_name]] <- mod_summary

}
allmods <- do.call(rbind, species_summs)
allmods$model <- factor(allmods$model, levels=c("model_H", "model_HA", "model_HS", "model_HAS", "model_A", "model_AS", "model_S")) # level the factors from most human to most machine
allmods$modelLabs <- factor(substr(allmods$model, 7,10), levels = c("H", "HA", "HS", "HAS", "A", "AS", "S")) 

 # detection parameters
 detprobs <- allmods %>% filter(measure=="p11" | measure=="p_aru11" | measure=="p_aru01")

 detprobPlot <- ggplot(detprobs[detprobs$measure=="p11",]) +
  geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
   geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), size=0.5, width=0.3) +
   theme_pubclean() +
  labs(y="p11", x="model", title=sp) +
   theme(legend.position = "none") +
   scale_color_manual(values=my_colors) +
   scale_y_continuous(limits=seq(0.0, 1.0))
 detprobPlot
 ggsave(plot = detprobPlot,
        filename = paste("COMB_minimal/results/figures/covarMod/p11", sp, year, Sys.Date(), "plot.png", sep="_"),
        width = 2, height = 1.75, units = "in", dpi = 300)

# # pARU -------------------------------------------------------------
#
pARU11Plot <- ggplot(detprobs[detprobs$measure=="p_aru11",]) +
  geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
  geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), size=0.5, width=0.3) +
  theme_pubclean() +
  labs(y="p_ARU11", title=sp, x="") +
  theme(legend.position = "none") +
  scale_color_manual(values=my_colors) +
  scale_y_continuous(limits=c(0, 0.5))
pARU11Plot
ggsave(plot = pARU11Plot, filename = paste("COMB_minimal/results/figures/pARU_11", species, year, Sys.Date(), "plot.png", sep="_"), width = 3.5, height = 2.5, units = "in", dpi = 300)
#
# # pARU01 -------------------------------------------------------------
#
pARU01Plot <- ggplot(detprobs[detprobs$measure=="p_aru01",]) +
  geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
  geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), size=0.5, width=0.3) +
  theme_pubclean() +
  labs(y="p_ARU01", x="model") +
  theme(legend.position = "none") +
  scale_color_manual(values=my_colors) +
  scale_y_continuous(limits=c(0, 0.18))
pARU01Plot
#
ggsave(plot = pARU01Plot, filename = paste("COMB_minimal/results/figures/pARU_01", species, year, Sys.Date(), "plot.png", sep="_"),width = 3.5, height = 2.5, units = "in", dpi = 300)
#
 combined_det_plot <- ggarrange(pARU11Plot, pARU01Plot, ncol=1)
ggsave(plot = combined_det_plot, filename = paste("COMB_minimal/results/figures/covarMod/combined_pARU", sp, year, Sys.Date(), "plot.png", sep="_"),width = 2, height = 3.5, units = "in", dpi = 300)
##year
# #}
# # overall psi -------------------------------------------------------------
#
psi.all <- allmods %>% filter(measure=="PropOcc")
tmp_tab <- all_naive_occs %>% filter(common_name==sp)
propOccPlot <- ggplot(psi.all[psi.all$measure=="PropOcc",]) +
  geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
  geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), width=0.3) +
  geom_hline(yintercept = colSums(tmp_tab[6])/81, linetype="dashed") + # naive detections by either source
  geom_hline(yintercept = colSums(tmp_tab[3])/81, linetype="twodash", color = "#59A14F") + # naive dets by PC only
  geom_hline(yintercept= colSums(tmp_tab[4])/81, linetype="twodash", color = "#E15759") + # naive dets by ARU only
  theme_pubclean() +

  scale_color_manual(values=my_colors) +
  labs(y="finite-sample occupancy", title=sp) +
  theme(legend.position = "none") #+
#  scale_y_continuous(limits=c(0, 85))
propOccPlot
ggsave(plot = propOccPlot, filename=paste("COMB_minimal/results/figures/covarMod/combined_psi", sp, year, Sys.Date(), "plot.png", sep="_"),width = 3, height = 3.5, units = "in", dpi = 300)


mu.all <- allmods %>% filter(grepl("mu", measure))
tmp_tab <- all_naive_occs %>% filter(common_name==species)

mu.all$facetLab <- ifelse(mu.all$measure=="mu[1]", "unoccupied", "occupied")
mu.Plot <- ggplot(mu.all[grepl("mu", mu.all$measure),]) +
  geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
  geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), width=0.3) +
  theme_pubclean() +
  
  scale_color_manual(values=my_colors) +
  labs(y="mu (mean score)", x="model", title=species) +
  facet_wrap(~facetLab) +
  theme(legend.position = "none") #+
#  scale_y_continuous(limits=c(0, 85))
mu.Plot
ggsave(plot = mu.Plot, filename=paste("COMB_minimal/results/figures/nullMod/mu", species, year, Sys.Date(), "plot.png", sep="_"),width = 3.5, height = 3, units = "in", dpi = 300)



# sigma -------------------------------------------------------------------


sigma.all <- allmods %>% filter(grepl("sigma", measure))
tmp_tab <- all_naive_occs %>% filter(common_name==species)

sigma.all$facetLab <- ifelse(sigma.all$measure=="sigma[1]", "unoccupied", "occupied")
sigma.Plot <- ggplot(sigma.all[grepl("sigma", sigma.all$measure),]) +
  geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
  geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), width=0.3) +
  #  geom_hline(yintercept = colSums(tmp_tab[6]), linetype="dashed") + # naive detections by either source
  #  geom_hline(yintercept = colSums(tmp_tab[3]), linetype="twodash", color = "#59A14F") + # naive dets by PC only
  #  geom_hline(yintercept= colSums(tmp_tab[4]), linetype="twodash", color = "#E15759") + # naive dets by ARU only
  theme_pubclean() +
  
  scale_color_manual(values=my_colors) +
  labs(y="sigma (variance of mu)", title=species, x="model") +
  facet_wrap(~facetLab) +
  theme(legend.position = "none") #+
#  scale_y_continuous(limits=c(0, 85))
sigma.Plot
ggsave(plot = sigma.Plot, filename=paste("COMB_minimal/results/figures/nullMod/sigma", species, year, Sys.Date(), "plot.png", sep="_"),width = 3.5, height = 3, units = "in", dpi = 300)


#}

# effect of fire ----------------------------------------------------------

beta1s <- allmods %>% filter(measure=="beta1")

betaPlot <- ggplot(beta1s) +
  geom_point(aes(x=modelLabs, y=mean, color=modelLabs)) +
  geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), size=0.5, width=0.3) +
  theme_pubclean() +
  scale_color_manual(values = my_colors) +
  geom_hline(yintercept=0) +
 # scale_y_continuous(limits = c(0,5))
  labs(y="posterior beta1", x="", title=sp) +
  theme(legend.position = "none")

ggsave(plot = betaPlot, filename=paste("COMB_minimal/results/figures/covarMod/burn_covar", sp, year, Sys.Date(), "plot.png", sep="_"),width = 3, height = 3.5, units = "in", dpi = 300)

#}

#colMeans(site_pos[1:5], na.rm=T) # how close the pc and aru estimates are to the combined model estimates likely differs by species
# do we have a simulation that gives different z matrices for pc, aru, and show that we return a reasonable psi?
fire.fxall <- allmods %>% filter(grepl("psi.pred.burn", measure))
fire.fxall$Xburn <- rep(jagsData$Xburn, 7)

#supp.labs <- c("Point Count Only", "ARU Only", "PC + ARU detections", "PC + ARU Scores")
#names(supp.labs) <- c("pconly", "aruonly", "noscores", "scoreonly")

fire.full.p <- fire.fxall %>% filter(modelLabs=="HAS") %>%
  ggplot() +
  geom_ribbon(aes(x=Xburn, ymin=X2.5., ymax=X97.5.), alpha=0.3) +
  geom_ribbon(aes(x=Xburn, ymin=X25., ymax=X75.), alpha=0.3) +
  geom_line(aes(x=Xburn, y=mean), linewidth=1.6) +
  #facet_wrap(~spp) +
  theme_pubclean() +
  labs(y="predicted occupancy probability (psi)", x = "Fire Severity", title=sp) +
  theme(legend.position = "none") 

fire.all.p <- fire.fxall %>% filter(modelLabs !="HAS") %>%
  ggplot() +
  geom_ribbon(aes(x=Xburn, ymin=X2.5., ymax=X97.5., fill=modelLabs), alpha=0.3) +
  geom_ribbon(aes(x=Xburn, ymin=X25., ymax=X75., fill=modelLabs), alpha=0.3) +
  geom_line(aes(x=Xburn, y=mean, color=modelLabs)) +
  #facet_wrap(~spp) +
  theme_pubclean() +
  labs(y="predicted occupancy probability (psi)", x = "Fire Severity") +
  theme(legend.position = "none") +
  scale_color_manual(values = my_colors) +
  scale_fill_manual(values=my_colors) +
  scale_x_continuous(breaks = c(0,1,2,3)) +
  facet_wrap(~modelLabs)

firefx.p <- ggarrange(fire.full.p, fire.all.p,
                      #  labels = c("A", "B", "C"),
                      ncol=2,
                      widths = c(1,1)
                      #  common.legend = F
)

ggsave(plot = firefx.p, filename = paste("COMB_minimal/results/figures/covarMod/firefx_allmods", sp, Sys.Date(), ".png") ,width = 7.5, height = 5, units = "in", dpi = 300)
}

