# code to explore Knockout Experiment data, as generated by "run_KO.R".
# "run_KO" generates a jags output object for every species x year x KO combo.

library(ggpubr)
library(tidyverse)

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


latlong <- read.csv("models/input/latlong.csv", header = F, col.names = c("siteid", "lat", "long"))

my_files <- list.files(path = "./COMB_minimal/results/jagsResults/jagsResults_no_covars/", pattern = "*.RData", full.names = T)
all_data <- lapply(my_files, load, .GlobalEnv)



# BIG LOOPS --------------------------------------------------------------------

extract_species_null <- function(obj_name) {
  strsplit(obj_name, "_")[[1]][4]
}

# Group JAGS objects by species
species_groups <- split(ls(pattern = "jagsResult_no_covars_"), sapply(ls(pattern = "jagsResult_no_covars"), extract_species_null))

# extract names of species datasets
extract_species <- function(obj_name) {
  strsplit(obj_name, "_")[[1]][2]
}



species_datasets <- split(ls(pattern = "data_"), sapply(ls(pattern="data_"), extract_species))


# Loop for generating naive occupancy tables ------------------------------

naive_occs <- list() # empty list for species' naive occs

for (species in names(species_datasets)) {
  species_dat <- mget(species_datasets[[species]]) # for making a table 
  
  for (species in names(species_dat)) {
    data <- species_dat[[species]] # obj is a single model
    
    site_pos <- data.frame(naive.pc.n = rowSums(data$y.pc, na.rm=TRUE), naive.aru.n = rowSums(data$y.aru, na.rm=TRUE))
    site_pos$naive.pc.pa <- ifelse(site_pos$naive.pc.n==0,0,1)
    site_pos$naive.aru.pa <- ifelse(site_pos$naive.aru.n==0,0,1)
    site_pos$both <- site_pos$naive.pc.pa + site_pos$naive.aru.pa
    site_pos$either <- ifelse(site_pos$both > 0, 1, 0)
    site_pos$siteid <- as.numeric(rownames(data$y.ind[,]))
    site_pos$common_name <- substr(species, 6,10) # need to extract the 4-letter code from "data_XXXX"
    site_pos$year <- year
    
    naive_occs[[species]] <- site_pos
  }
}
all_naive_occs <- do.call(rbind, naive_occs)

tab <- left_join(latlong, all_naive_occs)
write.csv(tab, file = "COMB_minimal/results/allWO_naiveOcc_2020_20250226.csv")

# det_tbl <- data.frame(mean = colMeans(site_pos[3:6], na.rm=T), 
#                       model=colnames(site_pos[3:6]), 
#                       measure="naivePsi") # how close the pc and aru estimates are to the combined model estimates likely differs by species

# define color scheme for models
# my_colors <- c("H" = "#0072B2",
#                "HA" = "#76B7B2",
#                "HS" = "#59A14F",
#                "HAS" = "#E69F00",
#                "A" = "#D55E00",
#                "AS"="#FF9DA7",
#                "S"="#E15759")

my_colors <- c("H" = "#59A14F",
               "HA" = "#76B7B2",
               "HS" = "#0072B2",
               "HAS" = "#CC79A7",
               "A" = "#E15759",
               "AS"="#FF9DA7",
               "S"="#E69F00")

# Loop for generating parameter figures -----------------------------------

for (species in names(species_groups)) {
  species_mods <- mget(species_groups[[species]]) # "species_mods" is a list of all models for that species 
  species_summs <- list() # empty list for all model summaries of a given species
  for (mod_name in names(species_mods)) {
    obj <- species_mods[[mod_name]] # obj is a single model
    
    mod_summary <- data.frame(obj$summary)
    mod_summary$model <- paste(str_split(mod_name, "_")[[1]][6],str_split(mod_name, "_")[[1]][7], sep="_")
    mod_summary$measure <- rownames(mod_summary)
    mod_summary$species <- species
    
    species_summs[[mod_name]] <- mod_summary
    
  }
  allmods <- do.call(rbind, species_summs)
  allmods$model <- factor(allmods$model, levels=c("model_H", "model_HA", "model_HS", "model_HAS", "model_A", "model_AS", "model_S")) # level the factors from most human to most machine
  allmods$modelLabs <- factor(substr(allmods$model, 7,10), levels = c("H", "HA", "HS", "HAS", "A", "AS", "S")) 
  
  # detection parameters
  detprobs <- allmods %>% filter(measure=="p11" | measure=="p_aru11" | measure=="p_aru01")
  
  detprobPlot <- ggplot(detprobs[detprobs$measure=="p11",]) +
    geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
    geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), size=0.5, width=0.3) +
    theme_pubclean() +
    labs(y="p11", x="model", title=species) +
    theme(legend.position = "none") +
    scale_color_manual(values=my_colors) +
    scale_y_continuous(limits=seq(0.0, 1.0))
  detprobPlot
  ggsave(plot = detprobPlot, 
         filename = paste("COMB_minimal/results/figures/nullMod/p11", species, "2020", Sys.Date(), "plot.png", sep="_"),
         width = 2, height = 1.75, units = "in", dpi = 300)
  
  # pARU -------------------------------------------------------------
  
  pARU11Plot <- ggplot(detprobs[detprobs$measure=="p_aru11",]) +
    geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
    geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), size=0.5, width=0.3) +
    theme_pubclean() +
    labs(y="p_ARU11", title=species, x="") +
    theme(legend.position = "none") +
    scale_color_manual(values=my_colors) +
    scale_y_continuous(limits=c(0, 0.5))
  pARU11Plot
  #ggsave(plot = pARU11Plot, filename = paste("COMB_minimal/results/figures/pARU_11", species, "2020", Sys.Date(), "plot.png", sep="_"), width = 3.5, height = 2.5, units = "in", dpi = 300)
  
  # pARU01 -------------------------------------------------------------
  
  pARU01Plot <- ggplot(detprobs[detprobs$measure=="p_aru01",]) +
    geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
    geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), size=0.5, width=0.3) +
    theme_pubclean() +
    labs(y="p_ARU01", x="model") +
    theme(legend.position = "none") +
    scale_color_manual(values=my_colors) +
    scale_y_continuous(limits=c(0, 0.18)) 
  pARU01Plot
  
  #ggsave(plot = pARU01Plot, filename = paste("COMB_minimal/results/figures/pARU_01", species, "2020", Sys.Date(), "plot.png", sep="_"),width = 3.5, height = 2.5, units = "in", dpi = 300)
  
  combined_det_plot <- ggarrange(pARU11Plot, pARU01Plot, ncol=1)
  ggsave(plot = combined_det_plot, filename = paste("COMB_minimal/results/figures/nullMod/combined_pARU", species, "2020", Sys.Date(), "plot.png", sep="_"),width = 2, height = 3.5, units = "in", dpi = 300)
  
  #}
  # overall psi -------------------------------------------------------------
  
  psi.all <- allmods %>% filter(measure=="PropOcc")
  tmp_tab <- all_naive_occs %>% filter(common_name==species)
  nOccPlot <- ggplot(psi.all[psi.all$measure=="PropOcc",]) +
    geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
    geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), width=0.3) +
    geom_hline(yintercept = colSums(tmp_tab[6])/81, linetype="solid", linewidth=0.6) + # naive detections by either source
    geom_hline(yintercept = colSums(tmp_tab[3])/81, linetype="longdash", color = "#59A14F", linewidth=0.6) + # naive dets by PC only
    geom_hline(yintercept= colSums(tmp_tab[4])/81, linetype="dotdash", color = "#E15759", linewidth=0.6) + # naive dets by ARU only
    theme_pubclean() +
    
    scale_color_manual(values=my_colors) +
    labs(y="prop. occupied sites", x="", title=species) +
    theme(legend.position = "none") +
    scale_y_continuous(limits=c(0, 1))
  nOccPlot
  ggsave(plot = nOccPlot, filename=paste("COMB_minimal/results/figures/nullMod/combined_psi", species, "2020", Sys.Date(), "plot.png", sep="_"),width = 3, height = 3.5, units = "in", dpi = 300)
  
#}


# mu1, mu2 ----------------------------------------------------------------

mu.all <- allmods %>% filter(grepl("mu", measure))
tmp_tab <- all_naive_occs %>% filter(common_name==species)

mu.all$facetLab <- ifelse(mu.all$measure=="mu[1]", "unoccupied", "occupied")
mu.Plot <- ggplot(mu.all[grepl("mu", mu.all$measure),]) +
  geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
  geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), width=0.3) +
#  geom_hline(yintercept = colSums(tmp_tab[6]), linetype="dashed") + # naive detections by either source
#  geom_hline(yintercept = colSums(tmp_tab[3]), linetype="twodash", color = "#59A14F") + # naive dets by PC only
#  geom_hline(yintercept= colSums(tmp_tab[4]), linetype="twodash", color = "#E15759") + # naive dets by ARU only
  theme_pubclean() +
  
  scale_color_manual(values=my_colors) +
  labs(y="mu (mean score)", x="model", title=species) +
  facet_wrap(~facetLab) +
  theme(legend.position = "none") #+
#  scale_y_continuous(limits=c(0, 85))
mu.Plot
ggsave(plot = mu.Plot, filename=paste("COMB_minimal/results/figures/nullMod/mu", species, "2020", Sys.Date(), "plot.png", sep="_"),width = 3.5, height = 3, units = "in", dpi = 300)



# sigma -------------------------------------------------------------------


sigma.all <- allmods %>% filter(grepl("sigma", measure))
tmp_tab <- all_naive_occs %>% filter(common_name==species)

sigma.all$facetLab <- ifelse(sigma.all$measure=="sigma[1]", "unoccupied", "occupied")
sigma.Plot <- ggplot(sigma.all[grepl("sigma", sigma.all$measure),]) +
  geom_point(aes(x=modelLabs, y=`mean`, color=modelLabs)) +
  geom_errorbar(aes(x=modelLabs, ymin=X2.5., ymax=X97.5., color=modelLabs), width=0.3) +
  #  geom_hline(yintercept = colSums(tmp_tab[6]), linetype="dashed") + # naive detections by either source
  #  geom_hline(yintercept = colSums(tmp_tab[3]), linetype="twodash", color = "#59A14F") + # naive dets by PC only
  #  geom_hline(yintercept= colSums(tmp_tab[4]), linetype="twodash", color = "#E15759") + # naive dets by ARU only
  theme_pubclean() +
  
  scale_color_manual(values=my_colors) +
  labs(y="sigma (variance of mu)", title=species, x="model") +
  facet_wrap(~facetLab) +
  theme(legend.position = "none") #+
#  scale_y_continuous(limits=c(0, 85))
sigma.Plot
ggsave(plot = sigma.Plot, filename=paste("COMB_minimal/results/figures/nullMod/sigma", species, "2020", Sys.Date(), "plot.png", sep="_"),width = 3.5, height = 3, units = "in", dpi = 300)



}



# Compare naive occupancy to estimated z ----------------------------------

z_HAWO_HAS <- data.frame(`jagsResult_no_covars_z_HAWO_2020_model_HAS_2025-03-18`$summary[1:81,])
z_HAWO_HA <- data.frame(`jagsResult_no_covars_z_HAWO_2020_model_HA_2025-03-18`$summary[1:81,])
z_HAWO_AS <- data.frame(`jagsResult_no_covars_z_HAWO_2020_model_AS_2025-03-18`$summary[1:81,])
z_HAWO_A <- data.frame(`jagsResult_no_covars_z_HAWO_2020_model_A_2025-03-18`$summary[1:81,])
z_HAWO_H <- data.frame(`jagsResult_no_covars_z_HAWO_2020_model_H_2025-03-18`$summary[1:81,])
z_HAWO_S <- data.frame(`jagsResult_no_covars_z_HAWO_2020_model_S_2025-03-18`$summary[1:81,])
z_HAWO_HS <- data.frame(`jagsResult_no_covars_z_HAWO_2020_model_HS_2025-03-18`$summary[1:81,])

naive_occs$data_HAWO$zHAS <- round(z_HAWO_HAS[,1],2)
naive_occs$data_HAWO$zHA <- round(z_HAWO_HA[,1],2)
naive_occs$data_HAWO$zAS <- round(z_HAWO_AS[,1],2)
naive_occs$data_HAWO$zA <- round(z_HAWO_A[,1],2)
naive_occs$data_HAWO$zH <- round(z_HAWO_H[,1],2)
naive_occs$data_HAWO$zS <- round(z_HAWO_S[,1],2)
naive_occs$data_HAWO$zHS <- round(z_HAWO_HS[,1],2)
View(naive_occs$data_HAWO)

write.csv(naive_occs$data_HAWO, "COMB_minimal/results/HAWO_zcompare.csv")
