#load("models/output/trialResults_max_pc_scores_2covars_all.rdata") # trial results generated by Mark 

# i ran each species separately
wos <- c("BBWO", "HAWO", "NOFL", "PIWO", "RBSA", "WHWO", "WISA")
woodpeckers <- list(bbwo, hawo, nofl, piwo, rbsa, whwo, wisa)
names(woodpeckers) <- wos

# finite sample psi

postpsi.fs <- rbind(woodpeckers$BBWO[13,], woodpeckers$HAWO[13,], woodpeckers$NOFL[13,], woodpeckers$PIWO[13,], woodpeckers$RBSA[13,], woodpeckers$WHWO[13,], woodpeckers$WISA[13,])

postpsi.fs$spp <- wos

ggplot(postpsi.fs) +
  geom_point(aes(x = spp, y = mean)) +
  geom_errorbar(aes(x = spp, ymin = `2.5%`, ymax = `97.5%`)) +
  geom_linerange(size = 2, aes(x = spp, ymin = `25%`, ymax = `75%`)) +
   ylim(0, 1) +
  labs(y = "post. finite sample psi", x = "species code", title = "Finite Sample psi") +
  theme_classic() +
  scale_color_manual(values = wes_palette("BottleRocket1", n = 2)) +
  theme(legend.position = "none", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) +
  coord_flip()

# mean psi

postpsi.mean <- rbind(woodpeckers$BBWO[14,], woodpeckers$HAWO[14,], woodpeckers$NOFL[14,], woodpeckers$PIWO[14,], woodpeckers$RBSA[14,], woodpeckers$WHWO[14,], woodpeckers$WISA[14,])

postpsi.mean$spp <- wos

ggplot(postpsi.mean) +
  geom_point(aes(x = spp, y = mean)) +
  geom_errorbar(aes(x = spp, ymin = `2.5%`, ymax = `97.5%`)) +
  geom_linerange(size = 2, aes(x = spp, ymin = `25%`, ymax = `75%`)) +
  ylim(0, 1) +
  labs(y = "post. mean psi", x = "species code", title = "Mean psi") +
  theme_classic() +
  scale_color_manual(values = wes_palette("BottleRocket1", n = 2)) +
  theme(legend.position = "none", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) +
  coord_flip()


# beta0 

postbeta0 <- rbind(woodpeckers$BBWO[1,], woodpeckers$HAWO[1,], woodpeckers$NOFL[1,], woodpeckers$PIWO[1,], woodpeckers$RBSA[1,], woodpeckers$WHWO[1,], woodpeckers$WISA[1,])
postbeta0$spp <- wos

ggplot(postbeta0) +
  geom_point(aes(x=spp, y=plogis(mean))) +
  geom_errorbar(aes(x = spp, ymin = plogis(`2.5%`), ymax = plogis(`97.5%`))) +
  geom_linerange(size = 2, aes(x = spp, ymin = plogis(`25%`), ymax = plogis(`75%`))) +
  ylim(0, 1) +
  labs(y = "posterior occupancy probability", x = "species code", title = "Post-fire occupancy") +
  theme_classic() +
  theme(legend.position = "none", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) +
  coord_flip()

# severity

postsev <- rbind(woodpeckers$BBWO[4,], woodpeckers$HAWO[4,], woodpeckers$NOFL[4,], woodpeckers$PIWO[4,], woodpeckers$RBSA[4,], woodpeckers$WHWO[4,], woodpeckers$WISA[4,])
postsev$overlap0 <- as.factor(postsev$overlap0)
postsev$spp <- wos

ggplot(postsev) +
  geom_point(aes(x = spp, y = mean, color = overlap0)) +
  geom_errorbar(aes(x = spp, ymin = `2.5%`, ymax = `97.5%`, color = overlap0)) +
  geom_linerange(size = 2, aes(x = spp, ymin = `25%`, ymax = `75%`, color = overlap0)) +
  geom_hline(yintercept = 0) +
 # ylim(-2, 2) +
  labs(y = "posterior estimate of assn with Burn Severity", x = "species code", title = "Relationship to burn severity") +
  theme_classic() +
  scale_color_manual(values = wes_palette("BottleRocket1", n = 2)) +
  theme(legend.position = "none", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) +
  coord_flip()

# canopy cover

postcc <- rbind(woodpeckers$BBWO[2,], woodpeckers$HAWO[2,], woodpeckers$NOFL[2,], woodpeckers$PIWO[2,], woodpeckers$RBSA[2,], woodpeckers$WHWO[2,], woodpeckers$WISA[2,])
postcc$overlap0 <- as.factor(postcc$overlap0)
postcc$spp <- wos

ggplot(postcc) +
  geom_point(aes(x = spp, y = mean, color = overlap0)) +
  geom_errorbar(aes(x = spp, ymin = `2.5%`, ymax = `97.5%`, color = overlap0)) +
  geom_linerange(size = 2, aes(x = spp, ymin = `25%`, ymax = `75%`, color = overlap0)) +
  geom_hline(yintercept = 0) +
  # ylim(-2, 2) +
  labs(y = "posterior estimate of assn with canopy cover", x = "species code", title = "Relationship to canopy cover") +
  theme_classic() +
  scale_color_manual(values = wes_palette("BottleRocket1", n = 2)) +
  theme(legend.position = "none", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) +
  coord_flip()

# canopy cover

postlgTree <- rbind(woodpeckers$BBWO[3,], woodpeckers$HAWO[3,], woodpeckers$NOFL[3,], woodpeckers$PIWO[3,], woodpeckers$RBSA[3,], woodpeckers$WHWO[3,], woodpeckers$WISA[3,])
postlgTree$overlap0 <- as.factor(postlgTree$overlap0)
postlgTree$spp <- wos

ggplot(postlgTree) +
  geom_point(aes(x = spp, y = mean, color = overlap0)) +
  geom_errorbar(aes(x = spp, ymin = `2.5%`, ymax = `97.5%`, color = overlap0)) +
  geom_linerange(size = 2, aes(x = spp, ymin = `25%`, ymax = `75%`, color = overlap0)) +
  geom_hline(yintercept = 0) +
  # ylim(-2, 2) +
  labs(y = "posterior estimate of assn with Large Trees", x = "species code", title = "Relationship to large trees") +
  theme_classic() +
  scale_color_manual(values = wes_palette("BottleRocket1", n = 2)) +
  theme(legend.position = "none", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) +
  coord_flip()
