load("models/output/woodpeckers_trialResults.rdata") # trial results generated by Mark 

#source('models/src/max_pc_scores_arubin_3covars.R')
library(wesanderson)
# i ran each species separately
wos <- c("BBWO", "HAWO", "NOFL", "PIWO", "RBSA", "WHWO", "WISA")

bbwo <- as.data.frame(trialResults$BBWO$summary)
hawo <- as.data.frame(trialResults$HAWO$summary)
nofl <- as.data.frame(trialResults$NOFL$summary)
piwo <- as.data.frame(trialResults$PIWO$summary)
rbsa <- as.data.frame(trialResults$RBSA$summary)
whwo <- as.data.frame(trialResults$WHWO$summary)
wisa <- as.data.frame(trialResults$WISA$summary)


woodpeckers <- list(bbwo, hawo, nofl, piwo, rbsa, whwo, wisa)
names(woodpeckers) <- wos

# finite sample psi

postpsi.fs <- rbind(woodpeckers$BBWO[13,], woodpeckers$HAWO[13,], woodpeckers$NOFL[13,], woodpeckers$PIWO[13,], woodpeckers$RBSA[13,], woodpeckers$WHWO[13,], woodpeckers$WISA[13,])

postpsi.fs$spp <- wos

ggplot(postpsi.fs) +
  geom_point(aes(x = spp, y = mean)) +
  geom_errorbar(aes(x = spp, ymin = `2.5%`, ymax = `97.5%`)) +
  geom_linerange(size = 2, aes(x = spp, ymin = `25%`, ymax = `75%`)) +
   ylim(0, 1) +
  labs(y = "post. finite sample psi", x = "species code", title = "Finite Sample psi") +
  theme_classic() +
  scale_color_manual(values = wes_palette("BottleRocket1", n = 2)) +
  theme(legend.position = "none", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) +
  coord_flip()

# mean psi

postpsi.mean <- rbind(woodpeckers$BBWO[11,], woodpeckers$HAWO[11,], woodpeckers$NOFL[11,], woodpeckers$PIWO[11,], woodpeckers$RBSA[11,], woodpeckers$WHWO[11,], woodpeckers$WISA[11,])

postpsi.mean$spp <- wos

ggplot(postpsi.mean) +
  geom_point(aes(x = spp, y = mean)) +
  geom_errorbar(aes(x = spp, ymin = `2.5%`, ymax = `97.5%`)) +
  geom_linerange(size = 2, aes(x = spp, ymin = `25%`, ymax = `75%`)) +
  ylim(0, 1) +
  labs(y = "post. mean psi", x = "species code", title = "Mean psi") +
  theme_classic() +
  scale_color_manual(values = wes_palette("BottleRocket1", n = 2)) +
  theme(legend.position = "none", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) +
  coord_flip()

# beta0 

postbeta0 <- rbind(woodpeckers$BBWO[1,], woodpeckers$HAWO[1,], woodpeckers$NOFL[1,], woodpeckers$PIWO[1,], woodpeckers$RBSA[1,], woodpeckers$WHWO[1,], woodpeckers$WISA[1,])
postbeta0$spp <- wos

ggplot(postbeta0) +
  geom_point(aes(x=spp, y=plogis(mean))) +
  geom_errorbar(aes(x = spp, ymin = plogis(`2.5%`), ymax = plogis(`97.5%`))) +
  geom_linerange(size = 2, aes(x = spp, ymin = plogis(`25%`), ymax = plogis(`75%`))) +
  ylim(0, 1) +
  labs(y = "posterior occupancy probability", x = "species code", title = "Post-fire occupancy intercept (unburned plots)") +
  theme_classic() +
  theme(legend.position = "none", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) +
  coord_flip()

# severity

postsev <- rbind(woodpeckers$BBWO[3,], woodpeckers$HAWO[3,], woodpeckers$NOFL[3,], woodpeckers$PIWO[3,], woodpeckers$RBSA[3,], woodpeckers$WHWO[3,], woodpeckers$WISA[3,])
postsev$overlap0 <- as.factor(postsev$overlap0)
postsev$spp <- wos

ggplot(postsev) +
  geom_point(aes(x = spp, y = mean, color = f)) +
  geom_errorbar(aes(x = spp, ymin = `2.5%`, ymax = `97.5%`, color = f)) +
  geom_linerange(size = 2, aes(x = spp, ymin = `25%`, ymax = `75%`, color = f)) +
  geom_hline(yintercept = 0) +
 # ylim(-2, 2) +
  labs(y = "posterior estimate of assn with Burn Severity", x = "species code", title = "Relationship to burn severity") +
  theme_classic() +
  #scale_color_manual(values = wes_palette("BottleRocket1", n = 2)) +
  theme(legend.position = "none", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) +
  coord_flip()

# canopy cover

postcc <- rbind(woodpeckers$BBWO[2,], woodpeckers$HAWO[2,], woodpeckers$NOFL[2,], woodpeckers$PIWO[2,], woodpeckers$RBSA[2,], woodpeckers$WHWO[2,], woodpeckers$WISA[2,])
postcc$overlap0 <- as.factor(postcc$overlap0)
postcc$spp <- wos

ggplot(postcc) +
  geom_point(aes(x = spp, y = mean, color = overlap0)) +
  geom_errorbar(aes(x = spp, ymin = `2.5%`, ymax = `97.5%`, color = overlap0)) +
  geom_linerange(size = 2, aes(x = spp, ymin = `25%`, ymax = `75%`, color = overlap0)) +
  geom_hline(yintercept = 0) +
  # ylim(-2, 2) +
  labs(y = "posterior estimate of assn with canopy cover", x = "species code", title = "Relationship to canopy cover") +
  theme_classic() +
  scale_color_manual(values = wes_palette("BottleRocket1", n = 2)) +
  theme(legend.position = "none", axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) +
  coord_flip()


# predictions for burn severity

# post-JAGS:

summary(jagsData$burn)
summary(jagsData$cover)
jagsData$Xburn = seq(0, 2.5, length.out=100)
jagsData$Xcover = seq(-2.75, 1.8, length.out=100)

for(k in 1:100) {
  logit(psi.pred.burn[k]) <- beta0 + beta2 * Xburn[k] # psi predictions for severity, holding canopy cover at mean
  logit(psi.pred.cov.ub[k]) <- beta0 + beta1 * Xcover[k] # psi predictions across cover, holding burn = 0 (unburned)
  logit(psi.pred.cov.b[k]) <- beta0 + beta1 * Xcover[k] + beta2 * 1 # psi predictions across cover, holding burn = 1 (avg burn)
  
}


# when done within JAGS:

bbwo[12:114,] # rows for burn severity predictions
burnSev <- list()
for (w in 1:length(woodpeckers)) {
  burnSev[[w]] <- woodpeckers[[w]][15:114,]
}

colnames(burnSev) <- colnames(woodpeckers)
names(burnSev) <- wos
burnSev <- lapply(1:length(burnSev), function(spp) cbind(burnSev[[spp]], spp))

burnSev_tidy <- as.data.frame(do.call(rbind, burnSev))
burnSev_tidy$spp <- rep(wos, each=100)
burnSev_tidy$Xburn <- rep(jagsData$Xburn, 7)

ggplot(burnSev_tidy) +
  geom_ribbon(aes(x=Xburn, ymin=`2.5%`, ymax=`97.5%`, fill=spp, alpha=0.2)) +
geom_line(aes(x=Xburn, y=mean)) +
  facet_wrap(~spp) +
  theme_classic() +
  labs(y="predicted occupancy probability (psi)", x = "RAVG score") +
  theme(legend.position = "none")

hawopred <- as.data.frame(jagsResult$summary[13:112,])
hawopred$Xburn <- jagsData$Xburn

ggplot(hawopred) +
  geom_ribbon(aes(x=Xburn, ymin=`2.5%`, ymax=`97.5%`, alpha=0.2)) +
  geom_line(aes(x=Xburn, y=mean)) +
  #facet_wrap(~spp) +
  theme_classic() +
  labs(y="predicted occupancy probability (psi)", x = "RAVG score", title="Hairy Woodpecker") +
  theme(legend.position = "none")

bbwopred <- as.data.frame(jagsResult$summary[13:112,])
bbwopred$Xburn <- jagsData$Xburn

ggplot(bbwopred) +
  geom_ribbon(aes(x=Xburn, ymin=`2.5%`, ymax=`97.5%`, alpha=0.2)) +
  geom_line(aes(x=Xburn, y=mean)) +
  #facet_wrap(~spp) +
  theme_classic() +
  labs(y="predicted occupancy probability (psi)", x = "RAVG score", title="Black-backed Woodpecker") +
  theme(legend.position = "none")


for (w in 1:length(burnSev)) {
plot(jagsData$Xburn, burnSev[[w]][,1])
  matlines(jagsData$Xburn, burnSev[[w]][,2])
}
par(mfrow=c(1,1))


matlines(jagsData$Xburn, bbwo[15:114, c(3,7)], col="grey", lty = 1) 

ggplot() +
  geom_line(aes(x=jagsData$Xburn, y=))